apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teleport-web
  namespace: teleport
  annotations:
    # Teleport сам управляє TLS через ACME — передаємо трафік as-is (SSL passthrough)
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
spec:
  ingressClassName: nginx
  rules:
    - host: teleport.nitra.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teleport-web
                port:
                  name: web
