name: StyleLint

on:
  push:
    branches:
      - dev
      - main
    paths:
      - '**/*.css'
      - '**/*.scss'
      - '**/*.vue'

  pull_request:
    branches:
      - dev
      - main
    paths:
      - '**/*.css'
      - '**/*.scss'
      - '**/*.vue'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  stylelint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-bun-deps

      - name: StyleLint
        run: npx stylelint '**/*.{css,scss,vue}' --fix
